branch-defaults:
  eb-deploy:
    environment: staging
environment-defaults:
  staging:
    branch: null
    repository: null
global:
  application_name: workshop-tonkotsu-nodejs
  branch: null
  default_ec2_keyname: null
  default_platform: node.js
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
