name: Azure Staging Deployment

on: push

jobs:
  staging:
    runs-on: ubuntu-latest
    - name: Setup Node 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: 'npm install, build, and test'
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present

    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: workshop-tonkotsu-nodejs
        publish-profile: ${{ secrets.AZURE_STAGING_SECRETS }}
