name: Deploy to Staging

on: 
  pull_request:
    branches-ignore: master

jobs:
  staging:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install
    - run: npm test
    - name: Generate deployment package
      run: zip deploy.zip *.js *.json *.html *.css
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v9
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: workshop-tonkotsu-nodejs
        environment_name: staging
        version_label: ${{ github.sha}}
        region: us-west-2
        deployment_package: deploy.zip

