name: Deploy to Staging

on: 
  pull_request:
    branches-ignore: master

jobs:
  staging:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install
    - run: npm test

    - uses: chrnorm/deployment-action@releases/v1
      name: Create GitHub deployment
      id: deployment
      with:
        token: "${{ github.token }}"
        target_url: http://staging.eba-82bp63q3.us-west-2.elasticbeanstalk.com/
        environment: staging
    - uses: hmanzur/actions-aws-eb@v1.0.0
      with:
        command: 'deploy staging'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: "us-west-2"

    - name: Update deployment status (success)
      if: success()
      uses: chrnorm/deployment-status@releases/v1
      with:
        token: "${{ github.token }}"
        target_url: http://staging.eba-82bp63q3.us-west-2.elasticbeanstalk.com/
        state: "success"
        deployment_id: ${{ steps.deployment.outputs.deployment_id }}

    - name: Update deployment status (failure)
      if: failure()
      uses: chrnorm/deployment-status@releases/v1
      with:
        token: "${{ github.token }}"
        target_url: http://staging.eba-82bp63q3.us-west-2.elasticbeanstalk.com/
        state: "failure"
        deployment_id: ${{ steps.deployment.outputs.deployment_id }}
